### ISSUE TITLE
Menu icon bar and perspective selector

### ISSUE THREAD

**Issue by phax** [YattaSolutions/eclipse-sandbox#2]
Hi!
I think this is a good idea and I'm happy to try it out (Windows version).
My question is solely: how do I get the Window menu, the menu icon bar and the perspective selector to show up?

Thanks

**Comment by phax** [comment]
I was able to show up the Package Exploer by using the shortcut, but a "Window" menu would help a lot :)

**Comment by FredericEbelshaeuser** [comment]
Hi,

You can enable the toolbar and perspective chooser through the Quick Access action. Press Ctrl+3 and type "toolbar"; you should get an entry "Toggle Main Toolbar Visibility" that will show the toolbar. Similarly, Ctrl+3, "perspective" let's you access "Customize Perspective", where you can re-enable the Window menu. 

I can see how the Window menu would help for customization, but may I ask what you are using perspectives for? We tried to strip down the UI as far as possible and are very interested in learning what people are missing and why.

**Comment by phax** [comment]
Okay - thanks for the information - this is tricky :)
I want a "simple" Java editor that can handle many (> 100) projects in different working sets at once without too many overhead. I use Git and Maven for source and dependency management.
I use perspectives to switch between regular editing mode and debug mode.
And managing many projects without a Package explorer is a pain in the ass - how do I switch between the project files???

**Comment by FredericEbelshaeuser** [comment]
Wow, that sounds tricky indeed :) Right now, the Sandbox only offers a very bare-bones text editor, so some assembly will be required. But that's exactly why we created this - to see what's actually needed and build a lean IDE with good UX from the ground up based on this input. 

So, the interesting question would be: What kind of Java editing features do you actually need? A full-fledged IDE with completion, compiler integration, refactoring and so on? Just an editor with basic syntax features like coloring and indentation support? Or something in between?

**Comment by FredericEbelshaeuser** [comment]
And since we started out on the menu structure: Here we tried to strip this down to the bare minimum as well. So it would be nice to know what you're missing (besides the Window menu), and how you would structure it. We tried to outline a menu structure for a more full-featured IDE (https://github.com/YattaSolutions/eclipse-sandbox/blob/master/Eclipse%20Menu%20Restructuring.xlsx). What do you think about it?

**Comment by phax** [comment]
I see there are a lot of questions :)
1. Window menu: must
2. Easy possibility to open the "Navigator" view to change between different files (Java independent) - very helpful
3. Java development: I like the "auto build" of Eclipse but I (personally) don't need all the overhead tools like DB support, Webapp support etc. Bare Git and Maven works for me. Of course syntax highlighting, line numbers, search (& replace), search references, open type/resource, code completion, comparison etc. is a must for me. No need to mention execution and debugging facilities...
4. Ad new menu structure:
    * Eclipse users are used to the term "Team" even though it is imho a too generic term. Using Versioning might indeed help.
    * There seem to be too many top-level menus overall.
    * And why is "Perform setzp tasks" in "Plugin-Ins" menu?
    * And "Show Maven repoistories" belongs more to "Build" than to "Connect"!?

**Comment by phax** [comment]
I suggest closing this issue, as my main problem was solved.
